### ISSUE TITLE
Report Inappropriate Predictions link not styled.

### ISSUE THREAD

**Issue by loligans** [Nass-O/DarkSearch#32]
The Report Inappropriate Predictions link is not stylized.
![Report Inappropriate Predictions link not stylized.](https://i.imgur.com/4raHD93.png)

```css
/* Report Inappropriate Predictions fix*/
.duf3 {
	background: #222!important;
}
```
The above code fixes the link to.

![Report Inappropriate Predictions link fix](https://i.imgur.com/KD6ciQE.png)
